### PR TITLE
Add support for download of an additional file required for install

### PR DESCRIPTION
**Pull request by CommonRaven**

### CODE REVIEW

**Comment by dweinstein** [comment]
Thanks for the contrib! Tests won't pass for external PRs. Can you mention an example pkg you tried this on?

**Comment by CommonRaven** [comment]
Sure thing. :)

I have tested it and found to be working with the following:
`com.rovio.baba` (Angry Birds 2)
`com.ea.game.fifa15_row` (FIFA 15)
`com.ea.game.nfs14_row` (Need for Speed™ No Limits)
And more.

**Comment by dweinstein** [comment]
(note to self) the file indexes come from `details.appDetails .[] .fileType` -- I'd like to add some tests here before merge. Also think there might be a cleaner way to add this without so much code duplication between this function and the others like it.

**Comment by dweinstein** [comment]
this is rolled into #45

**Pull request closed without merging**
