### PR TITLE
added request defaults

### PR DESCRIPTION
**Pull request by newhouse**

### CODE REVIEW

**Comment by newhouse** [comment]
Spelling errors fixed...

**Comment by dweinstein** [comment]
out of curiosity whats your specific use case for setting the requests default... guessing like a proxy or something?

**Comment by dweinstein** [comment]
thanks for your contribution

**Comment by dweinstein** [comment]
@newhouse your change is available as of version `gapi@1.1.17`

**Comment by newhouse** [comment]
@dweinstein Happy to contribute and thanks for your work!  And to answer your question: yeah, for us it was a proxy we wanted...but figured why not make anything allowable if you really wanted to.  The constructor arguments are starting to get a bit unwieldy and I thought about changing them to be more order-independent / kwarg-like (read: JSON), but didn't want to sacrifice backwards compatibility.  Maybe down the line.

**Comment by dweinstein** [comment]
FWIW I have a refactor branch that I can take that into consideration, see https://github.com/dweinstein/node-google-play/tree/refactor

**Pull request merged**
