### PR TITLE
new flow for downloadInfo

### PR DESCRIPTION
**Pull request by snirad**

### CODE REVIEW

**Comment by dweinstein** [comment]
is this supposed to replace #69

**Comment by snirad** [comment]
yep

**Comment by dweinstein** [comment]
The tests don’t pass with this change. It looks like there’s changes to the output from some of the functions so this would need to be a major version change?

**Comment by snirad** [comment]
hmm, i dont think it should break anything look these are the changes: 


`

    function getDownloadInfo(pkg, versionCode) {
        return getDownloadPurchaseInfo(pkg, versionCode)
            .then((purchaseInfo) => {
                if (purchaseInfo.downloadSize === null) {
                    return getDownloadDeliveryInfo(pkg, versionCode);
                } else {
                    return purchaseInfo;
                }
            })
    }

    /**
     * Get URL and cookie info for downloading a file from Google.
     * @param {String} pkg
     * @param {Number} versionCode
     */
    function getDownloadPurchaseInfo(pkg, versionCode) {
        const body = fmt('ot=1&doc=%s&vc=%d', pkg, versionCode);
        return executeRequestApi('purchase', {}, body).then(function (res) {
            assert(res.payload.buyResponse, 'expected buy response');
            if (!res.payload.buyResponse.purchaseStatusResponse) {
                const amount = res.payload.buyResponse.checkoutinfo.item.amount.formattedAmount;
                return Promise.reject(new AppNotFreeError('App is not free', amount));
            }
            assert(res.payload.buyResponse.purchaseStatusResponse, 'expected purchaseStatusResponse');
            const purchaseStatusResponse = res.payload.buyResponse.purchaseStatusResponse;
            const appDeliveryData = purchaseStatusResponse.appDeliveryData;
            assert(appDeliveryData, 'expected appDeliveryData');
            return appDeliveryData;
        });
    }


    /**
     * Get URL and cookie info for downloading a file from Google.
     * @param {String} pkg
     * @param {Number} versionCode
     */
    function getDownloadDeliveryInfo(pkg, versionCode) {
        return executeRequestApi('delivery', {ot: 1, doc: pkg, vc: versionCode}).then(function (res) {
            assert(res.payload.deliveryResponse, 'expected delivery response');
            const appDeliveryData = res.payload.deliveryResponse.appDeliveryData;
            assert(appDeliveryData, 'expected appDeliveryData');
            return appDeliveryData;
        });
    }
`

**Comment by dweinstein** [comment]
One example where it breaks is the signature field has gone missing

**Pull request closed without merging**
